version: 0.2
env:
  parameter-store:
    LOGIN: LOGIN
    HOST: HOST
    Organization: Organization
    Project: Project
    CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
    - cp ./settings.xml /root/.m2/settings.xml
  pre_build:
    commands:
    - apt-get update
    - apt-get install -y jq checkstyle
    - wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
    - tar xzvf apache-maven-3.9.4-bin.tar.gz
    - ln -s apache-maven-3.9.4 maven
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
    - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
    - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
    - mvn test
    - mvn checkstyle:checkstyle
    - echo "Installing JDK11 as its a dependency for sonarqube code analysis"
    - apt-get install -y openjdk-8-jdk
    - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - mvn sonar:sonar -Dsonar.login=460a4c9c3490aae685cd50ed2f34108a74dad2dc -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=hkhvprofileaws-repo -Dsonar.organization=hkhvprofileaws -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ -Dsonar.junit.reportsPath=target/surefire-reports/ -Dsonar.jacoco.reportsPath=target/jacoco.exec -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
    - sleep 5
    - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
    - cat result.json
    - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
