version: 0.2
env:
  parameter-store:
    LOGIN: LOGIN
    HOST: HOST
    Organization: Organization
    Project: Project
    CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
    - cp ./settings.xml /root/.m2/settings.xml
  pre_build:
    commands:
    - apt-get update
    - apt-get install -y jq checkstyle
    - wget https://dlcdn.apache.org/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
    - tar xzvf apache-maven-3.9.4-bin.tar.gz
    - ln -s apache-maven-3.9.4 maven
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
    - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
    - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
    - mvn test
    - mvn checkstyle:checkstyle
